import 'package:flutter/material.dart';

const Map<String, String> ANALYSIS_CATEGORY_MAP = {
  'Windows': '系统',
  'Program Files': '程序',
  'Program Files (x86)': '程序',
  'ProgramData': '程序数据',
  'Users': '用户',
  'PerfLogs': '系统日志',
  r'$Recycle.Bin': '回收站',
  'System Volume Information': '系统',
  'Inetpub': 'IIS',
  'Intel': '驱动',
  'AMD': '驱动',
  'NVIDIA': '驱动',
  'Python': '开发',
  'Git': '开发',
  'node_modules': '开发',
  'Android': '开发',
  'Miniconda3': '开发',
  'Anaconda3': '开发',
  'phpstudy_pro': '开发',
  'WWW': '开发',
  'Recovery': '恢复分区',
  'OneDrive': '云存储',
  'Dropbox': '云存储',
  'iCloudDrive': '云存储',
  'Steam': '游戏',
  'Epic Games': '游戏',
  'Battle.net': '游戏',
  'Origin': '游戏',
  'Ubisoft': '游戏',
  'Adobe': '设计',
  'Autodesk': '设计',
  'Blender Foundation': '设计',
  'Unity': '开发',
  'Unreal Engine': '开发',
  'JetBrains': '开发',
  'Visual Studio': '开发',
  'VSCode': '开发',
  'Code': '开发',
  'MySQL': '数据库',
  'PostgreSQL': '数据库',
  'MongoDB': '数据库',
  'Redis': '数据库',
  'Docker': '容器',
  'VirtualBox': '虚拟化',
  'VMware': '虚拟化',
  'Tencent': '腾讯',
  'Baidu': '百度',
  'Alibaba': '阿里',
  'NetEase': '网易',
  'Huawei': '华为',
};

const Map<String, Color> CATEGORY_COLORS = {
  '系统': Color(0xFFE94560),
  '程序': Color(0xFF0F3460),
  '程序数据': Color(0xFF533483),
  '用户': Color(0xFFE6A817),
  '开发': Color(0xFF16C79A),
  '游戏': Color(0xFFFF6B6B),
  '设计': Color(0xFF48DBFB),
  '驱动': Color(0xFFFECA57),
  '数据库': Color(0xFFFF9FF3),
  '虚拟化': Color(0xFF54A0FF),
  '容器': Color(0xFF5F27CD),
  '云存储': Color(0xFF01A3A4),
  'IIS': Color(0xFFF368E0),
  '系统日志': Color(0xFF2ED573),
  '回收站': Color(0xFFFF4757),
  '恢复分区': Color(0xFFC44569),
  '腾讯': Color(0xFFFF9F43),
  '百度': Color(0xFF54A0FF),
  '阿里': Color(0xFFF368E0),
  '网易': Color(0xFF2ED573),
  '华为': Color(0xFFE6A817),
  '其他': Color(0xFF636E72),
};

Color getCategoryColor(String category) {
  return CATEGORY_COLORS[category] ?? const Color(0xFF636E72);
}

String getCategoryByName(String name) {
  return ANALYSIS_CATEGORY_MAP[name] ?? '其他';
}
